project:
  type: website

website:
  title: "Dean Marchiori"
  site-url: "https://www.deanmarchiori.com"
  description: "Data Science and Statistical Consulting"
  open-graph: true
  image: "img/profile.png"
  twitter-card:
    image: "img/profile.png"
  page-footer:
    center: "Copyright 2025, Dean Marchiori"
  navbar:
    background: "#ffffff"
    search: false
    title: false
    pinned: false
    border: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: posts/index.qmd
      - text: "Consulting"
        href: consulting/index.qmd
format: 
  html: 
    page-layout: article
    theme: default 
    css: styles.css


