project:
  type: website

website:
  title: "Dean Marchiori"
  site-url: "https://www.deanmarchiori.com"
  description: "Data Science and Statistical Consulting"
  open-graph: true
  image: "https://www.deanmarchiori.com/img/profile.png"
  twitter-card:
    image: "https://www.deanmarchiori.com/img/profile.png"
  google-analytics: "UA-XXXXXXXX"
  navbar:
    right:
      - icon: rss
        href: posts/index.xml
    left:
      - href: index.qmd
        text: Home
      - href: consulting/index.qmd  
        text: Consulting
      - href: talks/index.qmd
        text: Talks
      - href: posts/index.qmd
        text: Blog
      - href: contact/index.qmd
        text: Contact
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/deanmarchiori/deanmarchiori.com
          - text: Report a Bug
            url:  https://github.com/deanmarchiori/deanmarchiori.com/issues
  page-footer:
    left: "Copyright 2023, Dean Marchiori"
  
format:
  html:
    theme: flatly
    css: styles.css
    toc: false



